=== apiis2/federfieh/etc/model.dtd
<!ENTITY GlobalColumns SYSTEM "GlobalColumns.xml">
<!ENTITY AccessRightsTables SYSTEM "AR.xml">
<!ENTITY OldAuthTables SYSTEM "OldAuth.xml">

<!ELEMENT model (general,table+)>
<!ELEMENT general EMPTY>
<!ATTLIST general
   dbdriver   (Pg|Oracle|CSV|InterBase|Sybase) "Pg"
   dbname     CDATA                            #REQUIRED
   dbhost     CDATA                            "localhost"
   dbport     CDATA                            "5432"
   dbuser     CDATA                            ""
   dbpassword CDATA                            ""
   dbencoding (unicode|latin1)                 #REQUIRED
   dbpg_enable_utf8 (0|1)                      "0"
>

<!ELEMENT table (column+,TABLE)>
<!ATTLIST table
   name         CDATA                            #REQUIRED
   struct_type  (mandatory|recommended|optional) "recommended"
   description  CDATA                           ""
>

<!ELEMENT column EMPTY>
<!ATTLIST column
   name        CDATA                            #REQUIRED
   struct_type (mandatory|recommended|optional) "optional"
   form_type   (editable|readonly|hidden)       "editable"
   ar_check    (0|1)                            "1"
   DATATYPE    (CHAR|HUGEINT|BIGINT|SMALLINT|DATE|TIME|TIMESTAMP|SMALLFLOAT|BIGFLOAT|BLOB|BOOL) "CHAR"
   LENGTH      CDATA                            "20"
   DATA        CDATA                            ""
   DESCRIPTION CDATA                            #REQUIRED
   DEFAULT     CDATA                            ""
   LABEL       CDATA                            ""
   CHECK       CDATA                            ""
   CHECK1      CDATA                            ""
   CHECK2      CDATA                            ""
   CHECK3      CDATA                            ""
   CHECK4      CDATA                            ""
   CHECK5      CDATA                            ""
   MODIFY      CDATA                            ""
>

<!ELEMENT TABLE (TRIGGER?,CONSTRAINTS?)> 

<!ELEMENT TRIGGER EMPTY>
<!ATTLIST TRIGGER
   PREINSERT   CDATA       ""
   POSTINSERT  CDATA       ""
   PREUPDATE   CDATA       ""
   POSTUPDATE  CDATA       ""
   PREDELETE   CDATA       ""
   POSTDELETE  CDATA       ""
>

<!ELEMENT CONSTRAINTS EMPTY>
<!ATTLIST CONSTRAINTS
   PRIMARYKEY  CDATA   ""
   SEQUENCE    CDATA   ""
   INDEX       CDATA   ""
>

=== apiis2/federfieh/etc/federvieh.xml
<?xml version="1.0"?>
<!DOCTYPE model SYSTEM "model.dtd">

<model >

    <general

        dbport      = "5432"
        dbuser      = "apiis_admin"
        dbname      = "federvieh"
        dbdriver    = "Pg"
        dbencoding  = "utf8"
        dbhost      = "localhost">
    </general>
    
    &AccessRightsTables;
    
<!-- _______standard_traits_content___________________________________ -->  
    <table

        name  = "standard_traits_content">

        &GlobalColumns;
        
        <column
            name         = "standard_traits_id"
            DESCRIPTION  = "Eindeutige ID des Merkmalstandards"
            CHECK        = "NotNull, ForeignKey standard_traits standard_traits_id"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>

        <column 
            name        = "traits_id" 
            DATATYPE    = "BIGINT" 
            LENGTH      = "20" 
            DESCRIPTION = "Bezeichnung des Merkmals-Standards" 
            CHECK       = "NotNull, ForeignKey traits traits_id">
        </column>
        
        <TABLE>
            <TRIGGER
                PREUPDATE  = " 'SetVersion version',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'"
                PREINSERT  = " 'SetVersion version',
                               'SetGuid guid',
                               'SetNode owner',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'">
            </TRIGGER> 
            <CONSTRAINTS 
                         INDEX="unique standard_traits_id traits_id">
            </CONSTRAINTS>
        </TABLE>
    </table>

<!-- _______standard_traits___________________________________ -->  
    <table

        name  = "standard_traits">

        &GlobalColumns;
        
        <column
            name         = "standard_traits_id"
            DESCRIPTION  = "Eindeutige ID des Merkmals"
            CHECK        = "NotNull"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>

        <column 
            name        = "label" 
            DATATYPE    = "CHAR" 
            LENGTH      = "20" 
            DESCRIPTION = "Bezeichnung des Standards" 
            CHECK       = "NotNull"  >
        </column>
        
        <column 
            name        = "description" 
            DATATYPE    = "CHAR" 
            LENGTH      = "20" 
            DESCRIPTION = "Beschreibung des Standards" 
            CHECK       = ""  >
        </column>
        
        <TABLE>
            <TRIGGER
                PREUPDATE  = " 'SetVersion version',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'"
                PREINSERT  = " 'SetColumn standard_traits_id seq_standard_traits__standard_traits_id',
                               'SetVersion version',
                               'SetGuid guid',
                               'SetNode owner',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'">
            </TRIGGER> 
            <CONSTRAINTS 
                         SEQUENCE="seq_standard_traits__standard_traits_id" 
                         INDEX="unique standard_traits_id, unique label">
            </CONSTRAINTS>
        </TABLE>
    </table>

<!-- _______standard_events___________________________________ -->  
    <table

        name  = "standard_events">

        &GlobalColumns;
        
        <column
            name         = "standard_events_id"
            DESCRIPTION  = "Eindeutige ID des Merkmals"
            CHECK        = "NotNull"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>
        <column 
            name        = "label" 
            DATATYPE    = "CHAR" 
            LENGTH      = "20" 
            DESCRIPTION = "Bezeichnung des Standards" 
            CHECK       = "NotNull"  >
        </column>
        <column 
            name        = "description" 
            DATATYPE    = "CHAR" 
            LENGTH      = "20" 
            DESCRIPTION = "Beschreibung des Standards" 
            CHECK       = ""  >
        </column>
        
        <column     name=   "db_event_type" DATATYPE="BIGINT" LENGTH="20" 
                    DESCRIPTION="Interne ID der Art der Pruefung" 
                    CHECK="NotNull, ForeignKey codes db_code class=EVENT"  >
        </column>
      
        <column
            name         = "standard_traits_id"
            DESCRIPTION  = "Eindeutige ID des Merkmalstandards"
            CHECK        = "NotNull, ForeignKey standard_traits standard_traits_id"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>
        <column
            name         = "standard_breeds_id"
            DESCRIPTION  = "Eindeutige ID des Rassestandards"
            CHECK        = "NotNull, ForeignKey standard_breeds standard_breeds_id"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>
        <column
            name         = "standard_users_id"
            DESCRIPTION  = "Eindeutige ID des Merkmalstandards"
            CHECK        = "ForeignKey standard_users standard_users_id"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>

        <TABLE>
            <TRIGGER
                PREUPDATE  = " 'SetVersion version',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'"
                PREINSERT  = " 'SetColumn standard_events_id seq_standard_events__standard_events_id',
                               'SetVersion version',
                               'SetGuid guid',
                               'SetNode owner',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'">
            </TRIGGER> 
            <CONSTRAINTS 
                         SEQUENCE   = "seq_standard_events__standard_events_id" 
                         INDEX      = "unique standard_events_id, unique label"
                         PRIMARYKEY = "CONCAT:label;REF_COL:standard_events_id">
            </CONSTRAINTS>
        </TABLE>
    </table>

<!-- _______standard_users___________________________________ -->  
    <table

        name  = "standard_users">

        &GlobalColumns;
        
        <column
            name         = "standard_users_id"
            DESCRIPTION  = "Eindeutige ID des Merkmals"
            CHECK        = "NotNull"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>

        <column 
            name        = "label" 
            DATATYPE    = "CHAR" 
            LENGTH      = "20" 
            DESCRIPTION = "Bezeichnung des Standards" 
            CHECK       = "NotNull"  >
        </column>
        
        <column 
            name        = "description" 
            DATATYPE    = "CHAR" 
            LENGTH      = "20" 
            DESCRIPTION = "Beschreibung des Standards" 
            CHECK       = ""  >
        </column>
        
        <TABLE>
            <TRIGGER
                PREUPDATE  = " 'SetVersion version',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'"
                PREINSERT  = " 'SetColumn standard_users_id seq_standard_users__standard_users_id',
                               'SetVersion version',
                               'SetGuid guid',
                               'SetNode owner',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'">
            </TRIGGER> 
            <CONSTRAINTS 
                         SEQUENCE="seq_standard_users__standard_users_id" 
                         INDEX="unique standard_users_id, unique label">
            </CONSTRAINTS>
        </TABLE>
    </table>

<!-- _______standard_users_content___________________________________ -->  
    <table

        name  = "standard_users_content">

        &GlobalColumns;
        
        <column
            name         = "standard_users_id"
            DESCRIPTION  = "Eindeutige ID des Usersstandards"
            CHECK        = "NotNull"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>

        <column 
            name        = "db_user" 
            DATATYPE    = "BIGINT" 
            LENGTH      = "20" 
            DESCRIPTION = "Bezeichnung des Users-Standards" 
            CHECK       = "NotNull">
        </column>
        
        <TABLE>
            <TRIGGER
                PREUPDATE  = " 'SetVersion version',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'"
                PREINSERT  = " 'SetVersion version',
                               'SetGuid guid',
                               'SetNode owner',
                               'SetNow last_change_dt',
                               'SetUser last_change_user'">
            </TRIGGER> 
            <CONSTRAINTS 
                         INDEX="standard_users_id, db_user">
            </CONSTRAINTS>
        </TABLE>
    </table>

    <!-- _______standard_breeds___________________________________ -->  
    <table

        name  = "standard_breeds">

        &GlobalColumns;
        
        <column
            name         = "standard_breeds_id"
            DESCRIPTION  = "Eindeutige ID des Merkmals"
            CHECK        = "NotNull"
            LENGTH       = "10"
            DATATYPE     = "BIGINT">
        </column>

        <column 
            name        = "label" 
            DATATYPE    = "CHAR" 
            LENGTH      = "20" 
            DESCRIPTION = "Bezeichnung des Standards" 
            CHECK       = "NotNull"  >
        </column>
        
        <column
